config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/inicio', to: 'welcome#index'
  
  resources :coins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  layout "admin"
  
  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #Caso faça o front no rails, existe um arquivo em 'views' com nome da 'action', neste caso 'index.html.erb'
  def index
    @meu_nome = "Raphael" #variável de sessão/instância
    #variável recebendo parâmetro pela URL. É importante ressaltar que o symbol dentro do params não precisa ser necessariamente igual a variável
    @meu_curso = params[:course]
    #utilizar & para enviar mais de um parâmetro pela URL
    @meu_nivel = params[:level]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    #helper para formatar as datas em qualquer local da aplicação
    def date_br(date_us)
        date_us.strftime("%d/%m/%Y")
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong>Description:</strong>
    <%= coin.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= coin.acronym %>
  </p>

  <p>
    <strong>Url image:</strong>
    <p><%= image_tag coin.url_image, width:25, height:25 %></p>
    <%= coin.url_image %>
    
  </p>

</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Exibir", @coin %> |
  <%= link_to "Voltar", coins_path %>
</div>

app/views/coins/index.html.erb
<h1>Moedas</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Sigla</th>
      <th>Imagem </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @coins.each do |coin| %>
        <tr>
          <td><%= coin.description %></td>
          <td><%= coin.acronym %></td>
          <!-- <td><img src="<%= coin.url_image %>" style="width: 25px; height: 25px;"></td> -->
          <td><%= image_tag coin.url_image, width: 25, height:25 %><td>
          <td><%= link_to 'Exibir', coin %></td>
          <td><%= link_to 'Alterar', edit_coin_path(coin) %></td>
          <td><%= link_to 'Apagar', coin, method: :delete, data: { confirm: 'Você tem certeza disso?'} %></td>
        </tr>
      <% end %>
  </tbody>
</table>
<%= link_to "Nova Moeda", new_coin_path %>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Voltar", coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to "Alterar", edit_coin_path(@coin) %> |
  <%= link_to "Voltar", coins_path %>

  <%= button_to "Apagar", @coin, method: :delete %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <h3> Página Administrativa </h3>
    <hr> 
    <!-- Importando a página _menu.html.erb -->
    <%= render "welcome/menu" %>

    <hr>
    <%= yield %>

    <hr>
    <h1> RODAPÉ </h1>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <h3> Testando a página <i>application.html.erb</i> </h3>
    <hr> 
    <!-- Importando a página _menu.html.erb -->
    <%= render "welcome/menu" %>
    <hr>

    <%= yield %>

    <hr>
    <h1> RODAPÉ </h1>
  </body>
</html>

app/views/welcome/_menu.html.erb
<!-- Esta página será re-utilizada por outras páginas através do método render "menu" -->
<!-- Helper: link_to -->
<ul>
    <li>
    <!-- Essa opção de coins_path está relacionada diretamente com o controller de 'coins'-->
        <%= link_to "Cadastro de Moedas", coins_path %>
    </li>
<!--
 Outros exemplos de se escrever caminho para o mesmo lugar    
    <li>
        <%= link_to "Cadastro de Moedas", "/coins" %>
    </li>
    <li>
        <a href="/coins">Cadastro de Moedas </a>
    </li>
-->
</ul>

app/views/welcome/index.html.erb
<h1> Seja Bem-Vindo! </h1>
<h3> <%= date_br(Date.today) %> </strong> </h3>
<hr>

<!-- O sinal de igual exibe o conteúdo Ruby na página -->

<p> A soma é: <%= 1 + 1 %> </p>
<p> Nome de trás pra frente <%= "Raphael".reverse %> </p>

<!-- Sem o sinal de igual não aparece o conteúdo entre a marcação -->
<% 
    #isso não será exibido
    a = "Variável escondida" 
%>

<p> Exibindo conteúdo da variável 'a': <strong> <%= a %> </strong> </p>
<p> Data: <strong> <%= Date.today %> </strong> </p>
<p> Data formatada: <strong> <%= Date.today.strftime("%d/%m/%Y")%> </strong> </p>
<p> Data formatada através de Helper criado: <strong> <%= date_br(Date.today) %> </strong> </p>

<hr>
<h3> Acessando variáveis globais e de sessão por URL </h3>
<p> Variável definida no código <strong> <%= @meu_nome %> </strong>. </p>

<p> O curso digitado na URL foi <strong> <%= @meu_curso %> </strong> e o nível é <strong> <%= @meu_nivel %> </strong>. </p>